import React, { useEffect, useState } from 'react';
import { ArrowUp, Instagram, Linkedin, Mail, MapPin, Phone } from 'lucide-react';

export default function Footer({ setActiveTab }) {
  const [showTop, setShowTop] = useState(false);
  useEffect(() => { const listener = () => setShowTop(window.scrollY > 500); window.addEventListener('scroll', listener, { passive: true }); return () => window.removeEventListener('scroll', listener); }, []);
  const go = tab => { setActiveTab(tab); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <footer className="site-footer"><div className="container footer-grid"><div className="footer-intro"><div className="footer-brand"><img src="/logo-vasant-valley.svg" alt="Vasant Valley School logo" /><strong>Vasant Valley School</strong></div><p>Education for life—rooted in ethical values, original thinking, and a sense of national and global citizenship.</p><div className="social-links"><a href="https://www.instagram.com/vasantvalleyschool/" aria-label="Vasant Valley School on Instagram"><Instagram /></a><a href="mailto:info@vasantvalley.edu.in" aria-label="Email Vasant Valley School"><Mail /></a><a href="https://www.linkedin.com" aria-label="Vasant Valley School on LinkedIn"><Linkedin /></a></div></div><div><h2>Explore</h2><button onClick={() => go('home')}>Home</button><button onClick={() => go('pillars')}>Learning Experience</button><button onClick={() => go('admissions')}>Admissions</button><button onClick={() => go('events')}>News & Events</button></div><div><h2>Contact</h2><p><MapPin /> Sector C, Vasant Kunj,<br />New Delhi 110070</p><p><Phone /> <a href="tel:+911141767940">+91 11 41767940</a></p><p><Mail /> <a href="mailto:info@vasantvalley.edu.in">info@vasantvalley.edu.in</a></p></div></div><div className="container footer-bottom"><span>© 2026 Vasant Valley School. All rights reserved.</span><span>Excellence in Deed</span></div>{showTop && <button className="back-to-top" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} aria-label="Back to top"><ArrowUp /></button>}</footer>;
}
